# # Steering double ranges for properties where you want sliders ...
# used in proxy writer
# possibly able to extend more:
# Global type defaults applied if no label override exists.


ranges:
  double_vector_single1:
    min: 1.0
    max: 99.0
  double_vector_array1:
    min: -10.0
    max: 10.0
  int_vector_array1:
    min: -10.0
    max: 10.0
  double_vector_single1:
    min: 11.0
    max: 55.0
    