# Resolve a reviewed dataset without requiring the Python generation environment.
# The lock pins both archive transport and manifest contents; local roots undergo
# the same manifest/file/schema checks as downloaded packages.
function(ippl_resolve_fem_oracles)
  file(READ "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/ipplTestData.lock.json" _lock)
  string(JSON _version GET "${_lock}" version)
  string(JSON _archive_hash GET "${_lock}" archiveSha256)
  string(JSON _manifest_hash GET "${_lock}" manifestSha256)
  string(JSON _url GET "${_lock}" url)

  set(IPPL_FEM_ORACLE_ROOT "" CACHE PATH "Existing extracted ipplTestData dataset")
  set(IPPL_FEM_ORACLE_ARCHIVE "" CACHE FILEPATH "Local pinned ipplTestData release archive")
  set(IPPL_FEM_ORACLE_DOWNLOAD ON CACHE BOOL "Allow fetching missing FEM oracle data")
  set(_root "${IPPL_FEM_ORACLE_ROOT}")
  if(NOT _root AND NOT IPPL_FEM_ORACLE_ARCHIVE)
    find_package(ipplTestData ${_version} EXACT CONFIG QUIET)
    if(ipplTestData_FOUND)
      set(_root "${ipplTestData_ROOT}")
    endif()
  endif()
  if(NOT _root)
    if(IPPL_FEM_ORACLE_ARCHIVE)
      get_filename_component(_url "${IPPL_FEM_ORACLE_ARCHIVE}" ABSOLUTE)
    elseif(NOT IPPL_FEM_ORACLE_DOWNLOAD OR NOT _url)
      message(FATAL_ERROR
        "FEM tests require ipplTestData ${_version}. Set IPPL_FEM_ORACLE_ROOT, "
        "IPPL_FEM_ORACLE_ARCHIVE, or install the pinned package. No usable download URL is configured.")
    endif()
    include(FetchContent)
    if(POLICY CMP0135)
      cmake_policy(SET CMP0135 NEW)
    endif()
    # A content-specific directory also avoids stale generated-header timestamps.
    set(_name "ippl_fem_oracle_${_archive_hash}")
    FetchContent_Declare(${_name} URL "${_url}" URL_HASH "SHA256=${_archive_hash}")
    FetchContent_MakeAvailable(${_name})
    set(_root "${${_name}_SOURCE_DIR}")
  endif()
  get_filename_component(_root "${_root}" ABSOLUTE)
  if(NOT EXISTS "${_root}/manifest.json")
    message(FATAL_ERROR "Missing FEM oracle manifest: ${_root}/manifest.json")
  endif()
  file(SHA256 "${_root}/manifest.json" _actual)
  if(NOT _actual STREQUAL _manifest_hash)
    message(FATAL_ERROR "FEM oracle manifest differs from pinned ipplTestData ${_version}")
  endif()
  file(READ "${_root}/manifest.json" _manifest)
  string(JSON _actual_version GET "${_manifest}" version)
  string(JSON _package GET "${_manifest}" package)
  string(JSON _format GET "${_manifest}" formatVersion)
  if(NOT _package STREQUAL "ipplTestData" OR NOT _actual_version STREQUAL _version OR NOT _format EQUAL 1)
    message(FATAL_ERROR "Unsupported FEM oracle package version/format")
  endif()
  string(JSON _count LENGTH "${_manifest}" files)
  math(EXPR _last "${_count}-1")
  foreach(_index RANGE 0 ${_last})
    string(JSON _file MEMBER "${_manifest}" files ${_index})
    string(JSON _expected GET "${_manifest}" files "${_file}" sha256)
    if(NOT EXISTS "${_root}/${_file}")
      message(FATAL_ERROR "Missing FEM oracle file: ${_root}/${_file}")
    endif()
    file(SHA256 "${_root}/${_file}" _actual)
    if(NOT _actual STREQUAL _expected)
      message(FATAL_ERROR "FEM oracle checksum mismatch: ${_file}")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_root}/${_file}")
  endforeach()
  file(SHA256 "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/FEMOracleData.h" _schema)
  string(JSON _expected_schema GET "${_manifest}" provenance schemaSha256)
  if(NOT _schema STREQUAL _expected_schema)
    message(FATAL_ERROR "FEM oracle schema differs from the pinned dataset contract")
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/ipplTestData.lock.json" "${_root}/manifest.json")
  set(FEM_ORACLE_PACKAGE_DIR "${_root}" PARENT_SCOPE)
  message(STATUS "FEM oracle dataset: ipplTestData ${_version} (${_root})")
endfunction()
